I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 18, in script
    $ play_music(introduction,3, volume)
  File "game/script.rpy", line 18, in <module>
    $ play_music(introduction,3, volume)
NameError: name 'volume' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 18, in script
    $ play_music(introduction,3, volume)
  File "/Applications/renpy-7.4.10-sdk/renpy/ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/Applications/renpy-7.4.10-sdk/renpy/python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 18, in <module>
    $ play_music(introduction,3, volume)
NameError: name 'volume' is not defined

macOS-10.16-x86_64-i386-64bit x86_64
Ren'Py 8.1.3.23091805
Good Morning Morgan 1.0
Tue Dec 31 21:52:24 2024
