I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 167, in script
    morg "Mina. It's me, Morgan. I'm here with the others."
  File "game/screens.rpy", line 1247, in execute
    screen minaphone():
  File "game/screens.rpy", line 1247, in execute
    screen minaphone():
  File "game/screens.rpy", line 1252, in execute
    add "gui/mainmenu/stars.png" xanchor .5 yanchor .5 xpos .5 ypos .5 at waveshader_stars2_phone, minapohone_pos
  File "game/screens.rpy", line 1252, in keywords
    add "gui/mainmenu/stars.png" xanchor .5 yanchor .5 xpos .5 ypos .5 at waveshader_stars2_phone, minapohone_pos
  File "game/screens.rpy", line 1252, in <module>
    add "gui/mainmenu/stars.png" xanchor .5 yanchor .5 xpos .5 ypos .5 at waveshader_stars2_phone, minapohone_pos
NameError: name 'minapohone_pos' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 167, in script
    morg "Mina. It's me, Morgan. I'm here with the others."
  File "/Applications/renpy-7.4.10-sdk/renpy/ast.py", line 930, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "/Applications/renpy-7.4.10-sdk/renpy/exports.py", line 1474, in say
    who(what, *args, **kwargs)
  File "/Applications/renpy-7.4.10-sdk/renpy/character.py", line 1352, in __call__
    self.do_display(who, what, cb_args=self.cb_args, dtt=dtt, **display_args)
  File "/Applications/renpy-7.4.10-sdk/renpy/character.py", line 1003, in do_display
    display_say(who,
  File "/Applications/renpy-7.4.10-sdk/renpy/character.py", line 693, in display_say
    rv = renpy.ui.interact(mouse='say', type=type, roll_forward=roll_forward)
  File "/Applications/renpy-7.4.10-sdk/renpy/ui.py", line 299, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "/Applications/renpy-7.4.10-sdk/renpy/display/core.py", line 3582, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "/Applications/renpy-7.4.10-sdk/renpy/display/core.py", line 4055, in interact_core
    root_widget.visit_all(lambda d : d.per_interact())
  File "/Applications/renpy-7.4.10-sdk/renpy/display/core.py", line 684, in visit_all
    d.visit_all(callback, seen)
  File "/Applications/renpy-7.4.10-sdk/renpy/display/core.py", line 684, in visit_all
    d.visit_all(callback, seen)
  File "/Applications/renpy-7.4.10-sdk/renpy/display/core.py", line 684, in visit_all
    d.visit_all(callback, seen)
  File "/Applications/renpy-7.4.10-sdk/renpy/display/screen.py", line 476, in visit_all
    callback(self)
  File "/Applications/renpy-7.4.10-sdk/renpy/display/core.py", line 4055, in <lambda>
    root_widget.visit_all(lambda d : d.per_interact())
  File "/Applications/renpy-7.4.10-sdk/renpy/display/screen.py", line 487, in per_interact
    self.update()
  File "/Applications/renpy-7.4.10-sdk/renpy/display/screen.py", line 680, in update
    self.screen.function(**self.scope)
  File "game/screens.rpy", line 1247, in execute
    screen minaphone():
  File "game/screens.rpy", line 1247, in execute
    screen minaphone():
  File "game/screens.rpy", line 1252, in execute
    add "gui/mainmenu/stars.png" xanchor .5 yanchor .5 xpos .5 ypos .5 at waveshader_stars2_phone, minapohone_pos
  File "game/screens.rpy", line 1252, in keywords
    add "gui/mainmenu/stars.png" xanchor .5 yanchor .5 xpos .5 ypos .5 at waveshader_stars2_phone, minapohone_pos
  File "game/screens.rpy", line 1252, in <module>
    add "gui/mainmenu/stars.png" xanchor .5 yanchor .5 xpos .5 ypos .5 at waveshader_stars2_phone, minapohone_pos
NameError: name 'minapohone_pos' is not defined

macOS-10.16-x86_64-i386-64bit x86_64
Ren'Py 8.1.3.23091805
Winter Game Jam 2024 The Winter Rally 1.0
Sun Dec 29 19:27:37 2024
